[package]
name = "world"
version = "0.1.0"
authors = ["Ivan Bodrov <ibodrov@gmail.com>"]

[dependencies]
specs = "*"
time = "*"
log = "*"

[dependencies.clippy]
version = "*"
optional = true

[features]
default = []
dev = ["clippy"]
