[map]
atlas="assets/atlas_aesomatica.toml"
#visible_tile_size=[64, 64]

[map.tiles]
dwarf = { tile = 1,   fg = [255, 100,   0, 255] }
grass = { tile = 46,  fg = [  0, 100,   0, 255] }
wall =  { tile = 178, fg = [255,   0,   0, 255] }
