[package]
name = "ui"
version = "0.1.0"
authors = ["Ivan Bodrov <ibodrov@gmail.com>"]

[dependencies]
glium = "*"
cgmath = "*"
time = "*"
image = "*"

[dependencies.world]
path = "../world"
version = "0.1.0"
